#color picker code generated by copilot with comments by me. Also reformated to use init and self instead of root and put functions inside app
import tkinter as tk
from tkinter import filedialog
from PIL import Image, ImageTk
from PIL import Image, ImageDraw
import random
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from PIL import Image
from pptx.oxml.ns import qn
from pptx.oxml.xmlchemy import OxmlElement
from pptx.enum.text import PP_ALIGN
from pptx.enum.shapes import MSO_SHAPE

class Colors_app(tk.Tk):
    def __init__(self):
        super().__init__() # Call the __init__() method of the parent class tk.Tk
        self.title("Color and Template Generator") # Set the title of the window

        self.canvas = tk.Canvas(self, width=600, height=400) #define canvas
        self.canvas.grid(row=1, column=0, columnspan=4, padx=10, pady=10)

        self.pickbtn = tk.Button(self, text="Open Image", command=self.open_image) #use open image function
        self.pickbtn.grid(row=0, column=0, columnspan=2, padx=10, pady=10, sticky='w')

        self.canvas.bind("<Button-1>", self.get_color) #use get color function

        self.randombtn = tk.Button(self, text="Random Color", command=self.random_color)
        self.randombtn.grid(row=0, column=2, columnspan=2, padx=10, pady=10, sticky='w')

    
    def open_image(self):
        file_path = filedialog.askopenfilename() #Open file
        if file_path:
            self.img = Image.open(file_path) #The chosen file
            self.img.thumbnail((600, 400))  # Resize for display
            self.tk_img = ImageTk.PhotoImage(self.img)

            self.canvas.delete("displayed_img")
            self.canvas.create_image(0, 0, anchor="nw", image=self.tk_img, tags="displayed_img") #place preview image to pick from in the top left
            self.canvas.image = self.tk_img  # Keep a reference
            self.canvas.img_data = self.img  # Store the PIL image for color picking
            self.canvas.mode = "image"

    def get_color(self,event):
        x, y = event.x, event.y #get coordinates for click
        if hasattr(self.canvas, 'img_data'):
            try:
                self.rgb = self.canvas.img_data.getpixel((x, y)) #gets pixel where clicked and its rgb value
                print(f"Clicked at ({x}, {y}) - Color: {self.rgb}")
            except IndexError:
                print("Clicked outside the image bounds.")
    
    def random_color(self):
        r = random.randint(0,255)
        g = random.randint(0,255)
        b = random.randint(0,255)
        print("Generated color: ", r,g,b)

        self.img = Image.new('RGB', (600,600), (r, g, b)) #create new image with original rgb as bg
        self.tk_img = ImageTk.PhotoImage(self.img)

        self.canvas.delete("")
        self.canvas.create_image(0, 0, anchor="nw", image=self.tk_img, tags="displayed_img")
        self.canvas.image = self.tk_img
        self.canvas.img_data = self.img
        self.canvas.mode = "color"


app = Colors_app()
app.mainloop()