#color picker code generated by copilot with comments by me. Also reformated to use init and self instead of root and put functions inside app
import tkinter as tk
from tkinter import filedialog
from tkinter import colorchooser
from PIL import Image, ImageTk
from PIL import Image, ImageDraw
import random
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from PIL import Image
from pptx.oxml.ns import qn
from pptx.oxml.xmlchemy import OxmlElement
from pptx.enum.text import PP_ALIGN
from pptx.enum.shapes import MSO_SHAPE

class Colors_app(tk.Tk):
    def __init__(self):
        super().__init__() # Call the __init__() method of the parent class tk.Tk
        self.title("Color and Template Generator") # Set the title of the window

        self.canvas = tk.Canvas(self, width=600, height=400) #define canvas
        self.canvas.grid(row=2, column=0, columnspan=4, padx=10, pady=10)

        current_rgb = (0, 0, 0)

        self.listbtn = tk.Button(self, text="Choose a Color", command=self.colorpicker) #use colorpicker function
        self.listbtn.grid(row=0, column=0, columnspan=2, padx=10, pady=10, sticky='we')
        
        self.pickbtn = tk.Button(self, text="Open Image", command=self.open_image) #use open image function
        self.pickbtn.grid(row=0, column=2, padx=10, pady=10, sticky='we')

        self.canvas.bind("<Button-1>", self.get_color) #use get color function

        self.randombtn = tk.Button(self, text="Random Color!", command=self.random_color) #choose a random color
        self.randombtn.grid(row=0, column=3, padx=10, pady=10, sticky='we')

        self.palettelbl = tk.Label(self, text="Choose a Palette Type:")
        self.palettelbl.grid(row=1, column=0, padx=10, pady=10, sticky='we')

        self.selected = tk.StringVar()
        self.r1 = tk.Radiobutton(self, text='Complementary', value='Complementary', variable=self.selected, command=self.complementary)
        self.r1.grid(row=1, column=1, padx=10, pady=10, sticky='we')
        self.r2 = tk.Radiobutton(self, text='Analogous', value='Analogous', variable=self.selected, command=self.analogous)
        self.r2.grid(row=1, column=2, padx=10, pady=10, sticky='we')
        self.r3 = tk.Radiobutton(self, text='Triadic', value='Triadic', variable=self.selected)
        self.r3.grid(row=1, column=3, padx=10, pady=10, sticky='we')
    
    def open_image(self):
        file_path = filedialog.askopenfilename() #Open file
        if file_path:
            self.img = Image.open(file_path) #The chosen file
            self.img.thumbnail((600, 400))  # Resize for display
            self.tk_img = ImageTk.PhotoImage(self.img)

            self.canvas.delete("displayed_img")
            self.canvas.create_image(0, 0, anchor="nw", image=self.tk_img, tags="displayed_img") #place preview image to pick from in the top left
            self.canvas.image = self.tk_img  # Keep a reference
            self.canvas.img_data = self.img  # Store the PIL image for color picking
            self.canvas.mode = "image"

    def get_color(self,event):
        global current_rgb
        x, y = event.x, event.y #get coordinates for click
        if hasattr(self.canvas, 'img_data'):
            try:
                current_rgb = self.canvas.img_data.getpixel((x, y)) #gets pixel where clicked and its rgb value
                print(f"Clicked at ({x}, {y}) - Color: {current_rgb}")
            except IndexError:
                print("Clicked outside the image bounds.")

    def random_color(self):
        global current_rgb

        current_rgb = (random.randint(0,255), random.randint(0,255), random.randint(0,255))
        print("Generated color: ", current_rgb)

        self.img = Image.new('RGB', (600,600), (current_rgb)) #create new image with original rgb as bg
        self.tk_img = ImageTk.PhotoImage(self.img)

        self.canvas.delete("")
        self.canvas.create_image(0, 0, anchor="nw", image=self.tk_img, tags="displayed_img")
        self.canvas.image = self.tk_img
        self.canvas.img_data = self.img
        self.canvas.mode = "color"

    def colorpicker(self):
        global current_rgb
        rgbwithhex = colorchooser.askcolor(title="Choose a color")
        current_rgb = rgbwithhex[0]
        print("Selected color:", current_rgb)

        self.img = Image.new('RGB', (600,600), (current_rgb)) #create new image with original rgb as background
        self.tk_img = ImageTk.PhotoImage(self.img)

        self.canvas.delete("")
        self.canvas.create_image(0, 0, anchor="nw", image=self.tk_img, tags="displayed_img")
        self.canvas.image = self.tk_img
        self.canvas.img_data = self.img
        self.canvas.mode = "color"
    
    def complementary(self):
        global current_rgb
        r, g, b = current_rgb

        newr = 255 - r
        newg = 255 - g #get new values
        newb = 255 - b

        print(newr, newg, newb)

        self.img = Image.new('RGB', (600,600), (current_rgb)) #create new image with original rgb as background
        self.draw = ImageDraw.Draw(self.img) #draw image
        self.draw.rectangle((0, 0, 300, 402), fill=(newr, newg, newb), outline=(newr, newg, newb))

        self.tk_img = ImageTk.PhotoImage(self.img)
        self.canvas.delete("")
        self.canvas.create_image(0, 0, anchor="nw", image=self.tk_img, tags="displayed_img")
        self.canvas.image = self.tk_img
        self.canvas.img_data = self.img
        self.canvas.mode = "color"

    def analogous(self):
        global current_rgb
        r, g, b = current_rgb

        newr1 = r
        newg1 = g + 31 #get new values
        if newg1 > 255:
            newg1 = g - 31 #make sure new values aren't higher than 255
        newb1 = b

        newr2 = r
        newg2 = g + 16
        if newg2 > 255:
            newg2 = g - 16
        newb2 = b

        print([newr1, newg1, newb1, newr2, newg2, newb2])

        self.img = Image.new('RGB', (600, 600), (r, g, b)) #create new image
        draw = ImageDraw.Draw(self.img) #draw
        draw.rectangle((0, 0, 600//3, 402), fill=(newr1, newg1, newb1)) #draw first analogous color rectangle
        draw.rectangle((600//3, 0, (600//3 + 600//3), 402), fill=(newr2, newg2, newb2)) #second

        self.tk_img = ImageTk.PhotoImage(self.img)
        self.canvas.delete("")
        self.canvas.create_image(0, 0, anchor="nw", image=self.tk_img, tags="displayed_img")
        self.canvas.image = self.tk_img
        self.canvas.img_data = self.img
        self.canvas.mode = "color"


app = Colors_app()
app.mainloop()